/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package marikuro;

import jade.Window;

public class App {
    public static void main(String[] args) {
        Window window = Window.get();
        window.run();
    }
}
